In [1]:
import pandas as pd
import numpy as np

In [2]:
price = pd.read_pickle('price_df_10s.pickle')
price

,BCHUSD,BTCUSD,EOSUSD,ETCUSD,ETHUSD,LTCUSD,XRPUSD,ZECUSD
timestamp,,,,,,,,
2017-08-02 08:53:30,550.00,2721.0,1.78970,14.90,223.77,42.657,0.17480,190.00
2017-08-02 08:53:40,550.00,2721.0,1.78970,14.90,223.77,42.657,0.17480,190.00
2017-08-02 08:53:50,550.00,2721.1,1.78970,14.90,223.77,42.657,0.17480,190.00
2017-08-02 08:54:00,550.00,2721.1,1.78970,14.90,223.77,42.657,0.17480,190.00
2017-08-02 08:54:10,550.00,2719.7,1.78970,14.90,223.77,42.657,0.17480,190.00
2017-08-02 08:54:20,550.00,2719.7,1.78890,14.90,223.77,42.657,0.17480,190.00
2017-08-02 08:54:30,400.00,2719.7,1.78640,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:54:40,400.00,2719.7,1.78640,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:54:50,400.00,2719.7,1.78640,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:55:00,375.00,2719.7,1.78640,14.90,223.77,42.665,0.17480,190.00
2017-08-02 08:55:10,375.00,2719.7,1.78870,14.90,223.77,42.665,0.17480,190.00
2017-08-02 08:55:20,375.00,2720.1,1.78870,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:55:30,360.00,2720.1,1.78640,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:55:40,360.00,2720.1,1.78640,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:55:50,360.00,2720.1,1.78640,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:56:00,360.00,2720.1,1.78860,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:56:10,360.00,2720.1,1.78650,14.90,223.77,42.658,0.17480,190.00
2017-08-02 08:56:20,400.00,2720.2,1.78640,14.90,224.07,42.658,0.17480,190.00
2017-08-02 08:56:30,410.00,2720.2,1.78640,14.90,224.04,42.658,0.17480,190.00
2017-08-02 08:56:40,410.00,2720.2,1.78640,14.90,224.04,42.658,0.17480,190.00
2017-08-02 08:56:50,400.00,2720.2,1.78640,14.90,224.04,42.663,0.17480,190.00
2017-08-02 08:57:00,400.00,2720.2,1.78730,14.90,224.04,42.663,0.17480,190.00
2017-08-02 08:57:10,400.00,2720.0,1.78680,14.90,224.00,42.663,0.17480,190.00
2017-08-02 08:57:20,400.00,2720.0,1.78680,14.90,224.00,42.663,0.17480,190.00
2017-08-02 08:57:30,400.00,2720.0,1.78650,14.90,224.00,42.665,0.17480,190.00
2017-08-02 08:57:40,400.00,2720.0,1.78650,14.88,224.00,42.658,0.17480,190.00
2017-08-02 08:57:50,400.00,2720.1,1.78650,14.88,223.89,42.683,0.17563,190.00
2017-08-02 08:58:00,380.00,2720.1,1.78660,14.90,223.89,42.658,0.17563,190.00
2017-08-02 08:58:10,380.00,2720.1,1.78660,14.90,223.89,42.658,0.17563,190.00
2017-08-02 08:58:20,390.01,2720.0,1.78640,14.90,223.83,42.658,0.17563,190.00
...,...,...,...,...,...,...,...,...
2018-04-02 18:08:40,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48362,195.71
2018-04-02 18:08:50,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48385,195.71
2018-04-02 18:09:00,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48430,195.71
2018-04-02 18:09:10,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48420,195.71
2018-04-02 18:09:20,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48408,195.71
2018-04-02 18:09:30,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48408,195.71
2018-04-02 18:09:40,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48420,195.71
2018-04-02 18:09:50,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48420,195.71
2018-04-02 18:10:00,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48420,195.71
2018-04-02 18:10:10,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48430,195.71
2018-04-02 18:10:20,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48430,195.71
2018-04-02 18:10:30,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48460,195.71
2018-04-02 18:10:40,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48466,195.71
2018-04-02 18:10:50,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48460,195.71
2018-04-02 18:11:00,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48460,195.71
2018-04-02 18:11:10,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48460,195.71
2018-04-02 18:11:20,1558.30,6957.9,5.67000,13.89,382.27,118.330,0.48460,195.71
2018-04-02 18:11:30,1558.30,6957.9,5.68170,13.89,382.27,118.330,0.48450,195.71
2018-04-02 18:11:40,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48450,195.71
2018-04-02 18:11:50,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48450,195.71
2018-04-02 18:12:00,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48419,195.71
2018-04-02 18:12:10,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48419,195.71
2018-04-02 18:12:20,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48419,195.71
2018-04-02 18:12:30,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48419,195.71
2018-04-02 18:12:40,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48449,195.71
2018-04-02 18:12:50,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48449,195.71
2018-04-02 18:13:00,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48429,195.71
2018-04-02 18:13:10,1558.30,6957.9,5.68178,13.89,382.27,118.330,0.48429,195.71
2018-04-02 18:13:20,1558.30,6957.9,5.68010,13.89,382.27,118.330,0.48466,195.71
2018-04-02 18:13:30,1558.30,6957.9,5.68010,13.89,382.27,118.330,0.48419,195.71

Alpha1：(-1 * CORR(RANK(DELTA(LOG(VOLUME), 1)), RANK(((CLOSE - OPEN) / OPEN)), 6))

Alpha2： (-1 * DELTA((((CLOSE - LOW) - (HIGH - CLOSE)) / (HIGH - LOW)), 1))

Alpha3： SUM((CLOSE=DELAY(CLOSE,1)?0:CLOSE-(CLOSE>DELAY(CLOSE,1)?MIN(LOW,DELAY(CLOSE,1)):MAX(HIGH,D ELAY(CLOSE,1)))),6)

Alpha4： ((((SUM(CLOSE, 8) / 8) + STD(CLOSE, 8)) < (SUM(CLOSE, 2) / 2)) ? (-1 * 1) : (((SUM(CLOSE, 2) / 2) < ((SUM(CLOSE, 8) / 8) - STD(CLOSE, 8))) ? 1 : (((1 < (VOLUME / MEAN(VOLUME,20))) || ((VOLUME / MEAN(VOLUME,20)) == 1)) ? 1 : (-1 * 1))))

Alpha5： (-1 * TSMAX(CORR(TSRANK(VOLUME, 5), TSRANK(HIGH, 5), 5), 3))

In [23]:
price['BTCUSD'][1:-1]

timestamp
2017-08-02 08:53:40    2721.0
2017-08-02 08:53:50    2721.1
2017-08-02 08:54:00    2721.1
2017-08-02 08:54:10    2719.7
2017-08-02 08:54:20    2719.7
2017-08-02 08:54:30    2719.7
2017-08-02 08:54:40    2719.7
2017-08-02 08:54:50    2719.7
2017-08-02 08:55:00    2719.7
2017-08-02 08:55:10    2719.7
2017-08-02 08:55:20    2720.1
2017-08-02 08:55:30    2720.1
2017-08-02 08:55:40    2720.1
2017-08-02 08:55:50    2720.1
2017-08-02 08:56:00    2720.1
2017-08-02 08:56:10    2720.1
2017-08-02 08:56:20    2720.2
2017-08-02 08:56:30    2720.2
2017-08-02 08:56:40    2720.2
2017-08-02 08:56:50    2720.2
2017-08-02 08:57:00    2720.2
2017-08-02 08:57:10    2720.0
2017-08-02 08:57:20    2720.0
2017-08-02 08:57:30    2720.0
2017-08-02 08:57:40    2720.0
2017-08-02 08:57:50    2720.1
2017-08-02 08:58:00    2720.1
2017-08-02 08:58:10    2720.1
2017-08-02 08:58:20    2720.0
2017-08-02 08:58:30    2720.0
                        ...
2018-04-02 18:08:30    6957.9
2018-04-02 18:08:40    6957.9
2018-04-02 18:08:50    6957.9
2018-04-02 18:09:00    6957.9
2018-04-02 18:09:10    6957.9
2018-04-02 18:09:20    6957.9
2018-04-02 18:09:30    6957.9
2018-04-02 18:09:40    6957.9
2018-04-02 18:09:50    6957.9
2018-04-02 18:10:00    6957.9
2018-04-02 18:10:10    6957.9
2018-04-02 18:10:20    6957.9
2018-04-02 18:10:30    6957.9
2018-04-02 18:10:40    6957.9
2018-04-02 18:10:50    6957.9
2018-04-02 18:11:00    6957.9
2018-04-02 18:11:10    6957.9
2018-04-02 18:11:20    6957.9
2018-04-02 18:11:30    6957.9
2018-04-02 18:11:40    6957.9
2018-04-02 18:11:50    6957.9
2018-04-02 18:12:00    6957.9
2018-04-02 18:12:10    6957.9
2018-04-02 18:12:20    6957.9
2018-04-02 18:12:30    6957.9
2018-04-02 18:12:40    6957.9
2018-04-02 18:12:50    6957.9
2018-04-02 18:13:00    6957.9
2018-04-02 18:13:10    6957.9
2018-04-02 18:13:20    6957.9
Freq: 10S, Name: BTCUSD, Length: 2102879, dtype: float64

In [9]:
price.index

DatetimeIndex(['2017-08-02 08:53:30', '2017-08-02 08:53:40',
               '2017-08-02 08:53:50', '2017-08-02 08:54:00',
               '2017-08-02 08:54:10', '2017-08-02 08:54:20',
               '2017-08-02 08:54:30', '2017-08-02 08:54:40',
               '2017-08-02 08:54:50', '2017-08-02 08:55:00',
               ...
               '2018-04-02 18:12:00', '2018-04-02 18:12:10',
               '2018-04-02 18:12:20', '2018-04-02 18:12:30',
               '2018-04-02 18:12:40', '2018-04-02 18:12:50',
               '2018-04-02 18:13:00', '2018-04-02 18:13:10',
               '2018-04-02 18:13:20', '2018-04-02 18:13:30'],
              dtype='datetime64[ns]', name='timestamp', length=2102881, freq='10S')

In [ ]:
btc = pd.DataFrame(price['BTCUSD'], co)